apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090

  - name: ClickHouse
    type: vertamedia-clickhouse-datasource
    url: http://db:8123
    database: default
    basicAuth: true
    basicAuthUser: default
    jsonData:
      basicAuthUser: default
      tlsSkipVerify: true
    secureJsonData:
      basicAuthPassword: password

  - name: ClickHouse-2
    type: grafana-clickhouse-datasource
    jsonData:
      defaultDatabase: default
      port: 9000
      host: db
      tlsSkipVerify: false
      username: default
    secureJsonData:
      password: password
